# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  # connect on port 13306
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provision :shell, :path => "Vagrant-install.sh"
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.provision "file", source: "build/", destination: "$HOME/educore/build"
  config.vm.provision "file", source: "src/", destination: "$HOME/educore/src"
  config.vm.provision "file", source: "gradle/", destination: "$HOME/educore/gradle"
  config.vm.provision "file", source: "settings.gradle", destination: "$HOME/educore/settings.gradle"
  config.vm.provision "file", source: "build.gradle", destination: "$HOME/educore/build.gradle"
  config.vm.provision "file", source: "gradlew", destination: "$HOME/educore/gradlew"
  config.vm.network "private_network", ip: "10.19.17.12"
  config.vm.hostname = "educore"
end
